name: Sync docs

on:
  push:
    branches:
      - main    
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Github Action
        uses: readmeio/rdme@6.5.0
        with:
          rdme: docs ./documentation/sync.md --key=${{ secrets.TEST }} --version=1.0

