name: Sync docs

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main    
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Github Action1
      - uses: readmeio/rdme@6.5.0
        with:
          rdme: docs ./documentation/sync.md --key=${{ secrets.TEST }} --version=1.0

